packages:
  all:
  # note the compiler and providers specifications
  # only suggest a priority order, they do not exclude other options
  # suggested priority for compilers.
    providers:
      mpi: [ cray-mpich ]
      pkgconfig: [ pkg-config ]
      fftw-api : [ cray-fftw ]
      blas: [cray-libsci ]
      lapack : [cray-libsci ]
      scalapack : [ cray-libsci ]


    permissions:
      read: world
      write: user

# don't build virtuals with an external provider
  mpi:
    buildable: False
  blas:
    buildable: False
  lapack:
    buildable: False
  scalapack:
    buildable: False
  fftw-api:
    buildable: False
  netcdf-cxx:
    buildable: False
  netcdf95:
    buildable: False
  
  gcc:
    externals:
      - spec: gcc@=11.2.0
        extra_attributes:
          compilers:
            c: cc
            cxx: CC
            fortran: ftn
        modules:
          - PrgEnv-gnu
          - gcc/11.2.0
          - xpmem
          - libfabric
          - craype-x86-rome
          - craype-network-ofi
      - spec: gcc@=7.5.0
        extra_attributes:
          compilers:
            c: /usr/bin/gcc
            cxx: /usr/bin/g++
            fortran: /usr/bin/gfortran
  
  cce:
    externals:
      - spec: cce@=16.0.1
        extra_attributes:
          compilers:
            c: cc
            cxx: CC
            fortran: ftn
        modules:
          - PrgEnv-cray
          - cce/16.0.1
          - xpmem
          - libfabric
          - craype-x86-rome
          - craype-network-ofi
  aocc:
    externals:
      - spec: aocc@=4.0.0
        extra_attributes:
          compilers:
            c: cc
            cxx: CC
            fortran: ftn
        modules:
          - PrgEnv-aocc
          - aocc/4.0.0
          - xpmem
          - libfabric
          - craype-x86-rome
          - craype-network-ofi


  netcdf-c:
    externals:
      - spec: netcdf-c@4.9.0.7+mpi%gcc
        modules:
          - cray-hdf5-parallel/1.12.2.7
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.7/gnu/9.1
      - spec: netcdf-c@4.9.0.7+mpi%cce
        modules:
          - cray-hdf5-parallel/1.12.2.7
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.7/crayclang/14.0
      - spec: netcdf-c@4.9.0.7+mpi%aocc
        modules:
          - cray-hdf5-parallel/1.12.2.7
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.7/aocc/3.2
    buildable: False

  netcdf-fortran:
    externals:
      - spec: netcdf-fortran@4.9.0.7%gcc
        modules:
          - cray-hdf5-parallel/1.12.2.7
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.7/gnu/9.1
      - spec: netcdf-fortran@4.9.0.7%cce
        modules:
          - cray-hdf5-parallel/1.12.2.1
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.7/crayclang/14.0
      - spec: netcdf-fortran@4.9.0.7%aocc
        modules:
          - cray-hdf5-parallel/1.12.2.7
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.7/aocc/3.2
    buildable: False

  netcdf-cxx4:
    externals:
      - spec: netcdf-cxx4@4.9.0.7%gcc
        modules:
          - cray-hdf5-parallel/1.12.2.7
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.7/gnu/9.1
      - spec: netcdf-cxx4@4.9.0.7%cce
        modules:
          - cray-hdf5-parallel/1.12.2.7
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.7/crayclang/14.0
      - spec: netcdf-cxx4@4.9.0.7%aocc
        modules:
          - cray-hdf5-parallel/1.12.2.7
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.7/aocc/3.2
    buildable: False

  parallel-netcdf:
    externals:
      - spec: parallel-netcdf@1.12.3.7%gcc
        modules:
          - cray-parallel-netcdf/1.12.3.7
        prefix: /opt/cray/pe/parallel-netcdf/1.12.3.7/gnu/9.1
      - spec: parallel-netcdf@1.12.3.7%cce
        modules:
          - cray-parallel-netcdf/1.12.3.7
        prefix: /opt/cray/pe/parallel-netcdf/1.12.3.7/crayclang/14.0
      - spec: parallel-netcdf@1.12.3.7%aocc
        modules:
          - cray-parallel-netcdf/1.12.3.7
        prefix: /opt/cray/pe/parallel-netcdf/1.12.3.7/aocc/3.2
    buildable: False

  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.27 +wrappers %gcc
      modules:
      - cray-mpich/8.1.27
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.27/ofi/gnu/9.1
    - spec: cray-mpich@8.1.27 +wrappers %cce
      modules:
      - cray-mpich/8.1.27
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.27/ofi/crayclang/14.0
    - spec: cray-mpich@8.1.27 +wrappers %aocc
      modules:
      - cray-mpich/8.1.27
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.27/ofi/aocc/3.0
    buildable: false
  
  hdf5:
    externals:
      - spec: hdf5@1.12.2.7+mpi%gcc
        modules:
          - cray-mpich/8.1.27
          - cray-hdf5-parallel/1.12.2.7
        prefix: /opt/cray/pe/hdf5-parallel/1.12.2.7/gnu/9.1
      - spec: hdf5@1.12.2.7+mpi%cce
        modules:
          - cray-mpich/8.1.27
          - cray-hdf5-parallel/1.12.2.7
        prefix: /opt/cray/pe/hdf5-parallel/1.12.2.7/crayclang/14.0
      - spec: hdf5@1.12.2.7+mpi%aocc
        modules:
          - cray-mpich/8.1.27
          - cray-hdf5-parallel/1.12.2.7
        prefix: /opt/cray/pe/mpich/8.1.27/ofi/aocc/3.0
    buildable: False

  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
    buildable: false

  libfabric:
    externals:
    - spec: libfabric@1.12.1.2.2.0.0
      modules:
      - libfabric/1.12.1.2.2.0.0
      prefix: /opt/cray/libfabric/1.12.1.2.2.0.0
    buildable: false

  cray-fftw:
    externals:
    - spec: cray-fftw@3.3.10.5
      modules:
      - craype-x86-rome
      - cray-fftw/3.3.10.5
      prefix: /opt/cray/pe/fftw/3.3.10.5/x86_rome
    buildable: false

  cray-libsci:
    externals:
    - spec: cray-libsci@23.09.1.1%gcc
      modules:
      - cray-libsci/23.09.1.1
      prefix: /opt/cray/pe/libsci/23.09.1.1/GNU/10.3/x86_64
    - spec: cray-libsci@23.09.1.1%cce
      modules:
      - cray-libsci/23.09.1.1
      prefix: /opt/cray/pe/libsci/23.09.1.1/CRAY/12.0/x86_64
    - spec: cray-libsci@22.08.1.1%aocc
      modules:
      - cray-libsci/22.12.1.1
      prefix: /opt/cray/pe/libsci/23.09.1.1/AOCC/3.2/x86_64
 
  python:
    externals:
     - spec: python@3.10.10
       prefix: /opt/cray/pe/python/3.10.10
  
  py-numpy:
    externals:
     - spec: py-numpy@1.23.5
       prefix: /opt/cray/pe/python/3.10.10
  
  py-mpi4py:
    externals:
     - spec: py-mpi4py@3.1.4
       prefix: /opt/cray/pe/python/3.10.10
    buildable: false
    
  py-scipy:
    externals:
     - spec: py-scipy@1.10.0
       prefix: /opt/cray/pe/python/3.10.10
    
  py-cython:
    externals:
     - spec: py-cython@0.29.36
       prefix: /opt/cray/pe/python/3.10.10
  
  py-setuptools:
    externals:
     - spec: py-setuptools@65.5.0
       prefix: /opt/cray/pe/python/3.10.10
  
  py-setuptools-scm:
    externals:
     - spec: py-setuptools-scm@7.1.0
       prefix: /opt/cray/pe/python/3.10.10

